spring:
  datasource:
    username: root
    password: 123456789
    url: jdbc:mysql://localhost:3306/front?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.zlv.admin.domain
  mapper-locations: classpath:mapper/*.xml
server:
  port: 1234
jwt:
  tokenHeader: Authorization #jwt存储的请求头
  secret: admin #jwt秘钥
  expiration: 60000 #jwt有效时长
  tokenHead: Bearer #jwt负载开头

